models:
    image: tp33/django
    external_links:
      -  mysql:db
    container_name: models_container
    volumes:
      - "$PWD/app:/app"
    command: bash -c "pip install -r /app/requirements.txt && python /app/homestarter/manage.py makemigrations api && python /app/homestarter/manage.py migrate && mod_wsgi-express start-server --working-directory /app/homestarter --reload-on-changes --log-to-terminal /app/homestarter/homestarter/wsgi.py"
    ports:
      - "8001:8000"


web:
   container_name: ecovi_web
   image: tp33/django
   links:
      - models:models_api
   ports:
      - "8000:8000"
   volumes:
      - ~/Desktop/pentagon/app:/app
   command: bash -c "pip install -r /app/requirements.txt && python /app/homestarter/manage.py makemigrations && python /app/homestarter/manage.py migrate && mod_wsgi-express start-server --working-directory /app/homestarter/ /app/homestarter/homestarter/wsgi.py"

