branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: ecovi
  branch: null
  default_ec2_keyname: eb-ecovi
  default_platform: Docker 17.03.2-ce
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
